import test from 'node:test';
import assert from 'node:assert/strict';
import {preset,PRESETS,validateCase,parameters,rasterize,equilibrium,History,outline,contains} from '../src/model.js';
import {CPUSolver} from '../src/cpu.js';
import {diagnose,fieldCSV,fieldVTK} from '../src/diagnostics.js';
function periodic(nx=48,ny=48,nu=.1,collision='trt') {const tau=.5+3*nu;return {nx,ny,n:nx*ny,u:.03,nuL:nu,tau,omega:1/tau,odd:collision==='trt'?1/(.5+(3/16)/(tau-.5)):1/tau,mode:2,profile:0,dx:1/nx,dt:1,speedScale:1,pressureScale:1,actualHeight:1};}
function moments(f,n,i){let rho=0,x=0,y=0;const cx=[0,1,0,-1,0,1,-1,-1,1],cy=[0,0,1,0,-1,1,1,-1,-1];for(let q=0;q<9;q++){const v=f[q*n+i];rho+=v;x+=v*cx[q];y+=v*cy[q];}return {rho,x,y};}
test('All six supplied cases satisfy strict schema and lattice stability constraints',()=>{for(const item of PRESETS){const c=validateCase(preset(item.id)),p=parameters(c);assert(p.tau>.505&&p.tau<3);assert.equal(rasterize(c,p).length,p.n);}});
test('Equilibrium exactly reproduces prescribed density and momentum',()=>{const rho=1.02,ux=.043,uy=-.017;const f=Float64Array.from({length:9},(_,q)=>equilibrium(rho,ux,uy,q)),m=moments(f,1,0);assert(Math.abs(m.rho-rho)<1e-14);assert(Math.abs(m.x-rho*ux)<1e-14);assert(Math.abs(m.y-rho*uy)<1e-14);});
for(const collision of ['trt','bgk'])test(`${collision.toUpperCase()}: periodic uniform equilibrium is stationary`,()=>{const p=periodic(32,32,.1,collision),solver=new CPUSolver(p,new Uint32Array(p.n));solver.step(300);const d=diagnose(solver.field,null,p,300);assert(d.finite);assert(Math.abs(d.meanRho-1)<2e-6);assert(Math.abs(d.maxU-p.u)<2e-6);assert(Math.abs(d.range.uy[1])<1e-6);});
for(const collision of ['trt','bgk'])test(`${collision.toUpperCase()}: shear-wave decay recovers analytical viscosity`,()=>{
  const p=periodic(48,48,.1,collision),a=.016,k=2*Math.PI/p.ny,steps=600;
  const solver=new CPUSolver(p,new Uint32Array(p.n),(x,y)=>({rho:1,ux:a*Math.sin(k*y),uy:0}));solver.step(steps);
  let amplitude=0;for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++)amplitude+=solver.field[(y*p.nx+x)*4]*Math.sin(k*y);amplitude*=2/p.n;
  const expected=a*Math.exp(-p.nuL*k*k*steps),rel=Math.abs(amplitude/expected-1);console.log(`${collision} shear decay: measured=${amplitude.toExponential(8)}, analytical=${expected.toExponential(8)}, relative error=${(100*rel).toFixed(4)}%`);assert(rel<.015,`Relative error ${rel}`);
  const d=diagnose(solver.field,null,p,steps);assert(Math.abs(d.meanRho-1)<2e-5);
});
test('Closed lid-driven cavity conserves mass and produces recirculation',()=>{const c=preset('cavity');c.domain.nx=48;const p=parameters(c),mask=rasterize(c,p),solver=new CPUSolver(p,mask);solver.step(1200);const d=diagnose(solver.field,null,p,1200);console.log(`Cavity mean density: ${d.meanRho.toFixed(9)}, min ux: ${d.range.ux[0]}, max ux: ${d.range.ux[1]}`);assert(d.finite&&!d.unstable);assert(Math.abs(d.meanRho-1)<2e-4);assert(d.range.ux[0]<0);assert(d.range.ux[1]>0);for(let i=0;i<p.n;i++)if(mask[i])assert.equal(solver.field[i*4],0);});
test('Zou–He tunnel boundaries recover prescribed inlet velocity and outlet density',()=>{const c=preset('channel');c.domain.nx=96;c.flow.profile='uniform';const p=parameters(c),solver=new CPUSolver(p,rasterize(c,p));solver.step(1000);const d=diagnose(solver.field,null,p,1000);assert(d.finite&&!d.unstable);for(let y=2;y<p.ny-2;y++){assert(Math.abs(solver.field[(y*p.nx)*4]-p.u)<2e-6);assert(Math.abs(solver.field[(y*p.nx+p.nx-1)*4+2]-1)<2e-6);}});
test('Rasterization distinguishes body interior from fluid and fixed domain walls',()=>{const c=preset('cylinder'),p=parameters(c),mask=rasterize(c,p),body=c.bodies[0];assert(contains(outline(body),body.x,body.y));assert(!contains(outline(body),body.x+body.width,body.y));assert(mask[Math.round(body.y/p.dx)*p.nx+Math.round(body.x/p.dx)]);assert(!mask[Math.floor(p.ny/2)*p.nx+p.nx-5]);assert(mask[4]);});
test('Case validation rejects nonphysical, oversized and malformed input',()=>{for(const change of [c=>c.domain.nx=100000,c=>c.domain.length=0,c=>c.fluid.viscosity=-1,c=>c.flow.speed=NaN,c=>c.bodies[0].width=-.1,c=>c.display.rangeMin=NaN,c=>c.flow.mode='compressible',c=>c.domain.height=20]){const c=preset();change(c);assert.throws(()=>validateCase(c));}});
test('History undo / redo creates independent snapshots',()=>{const h=new History(3),a=preset();h.push(a);const b=structuredClone(a);b.name='changed';const prev=h.undo(b);assert.equal(prev.name,a.name);prev.name='mutated';assert.equal(h.redo(prev).name,'changed');assert.equal(a.name,'Airfoil water tunnel');});
test('CSV and VTK serialize physical velocity and gauge pressure',()=>{const p=periodic(4,4),solver=new CPUSolver(p,new Uint32Array(p.n));const csv=fieldCSV(solver.field,p),vtk=fieldVTK(solver.field,p);assert.equal(csv.split('\n').length,p.n+1);assert(csv.includes('gauge_pressure_Pa'));assert(vtk.includes('DIMENSIONS 4 4 1'));assert(vtk.includes('VECTORS velocity float'));assert(vtk.includes('SCALARS solid int 1'));});
