import {preset,PRESETS,validateCase,parameters,rasterize,clone,uid,History,contains,outline,clamp} from './model.js';
import {GPUSolver,WorkerSolver,CooperativeSolver} from './gpu.js';
import {diagnose,sample,fieldCSV,fieldVTK} from './diagnostics.js';
import {Viewport,FIELDS,PALETTES,formatNumber} from './viewport.js';
import {icon,hydrate,escapeHTML as esc} from './icons.js';
import {renderRibbon,renderTree,renderInspector,renderBottom,syncUI} from './ui.js';
const $=q=>document.querySelector(q), query=new URLSearchParams(location.search);
const state={case:preset(),p:null,mask:null,engine:null,renderer:null,field:null,diag:null,iteration:0,snapshotIteration:0,records:[],logs:[],history:new History(),selected:null,node:'run',panel:'solution',ribbonTab:'home',bottom:'convergence',tool:'select',folded:new Set(),running:false,loading:true,busy:false,backend:'Initializing',generation:0,steadyCount:0,lastConvergenceIteration:0};
state.p=parameters(state.case);
const view=new Viewport(()=>state);
let lastStats=0,lastSnapshot=0,snapshotPending=false,lastPerf=performance.now(),frames=0,lastPerfIteration=0,drag=null,polygonPoints=[],wasRunning=false;
const number=v=>formatNumber(v,4);
function log(message,level='info'){state.logs.push({time:new Date().toLocaleTimeString('en-GB'),message,level});if(state.logs.length>400)state.logs.shift();$('#log-count').textContent=state.logs.length;if(state.bottom==='console')renderBottom(state);}
function toast(message,kind='success'){const item=document.createElement('div');item.className='toast '+kind;item.textContent=message;$('#toasts').append(item);setTimeout(()=>item.remove(),kind==='error'?9000:5000);}
function status(message){$('#status-message').textContent=message;}
function persist(){try{localStorage.setItem('fluxlab-case-v1',JSON.stringify(state.case));}catch{status('Local autosave unavailable; export a case file.');}}
function refresh(full=true){syncUI(state);if(full){renderRibbon(state);renderTree(state);renderInspector(state);}renderBottom(state);updateLegend();}
function updateLegend(){const [lo,hi]=view.getRange();$('#legend-labels').innerHTML=Array.from({length:6},(_,i)=>`<span>${formatNumber(hi-(hi-lo)*i/5)}</span>`).join('');const colors=PALETTES[state.case.display.palette];$('#legend-gradient').style.background=`linear-gradient(to top,${colors.map(c=>`rgb(${c.map(v=>Math.round(v*255)).join(',')})`).join(',')})`;}
function showPanel(panel,node=panel){state.panel=panel;state.node=node;if(panel!=='body')state.selected=null;renderInspector(state);renderTree(state);if(innerWidth<=900)$('.inspector-pane').classList.add('mobile-open');}
function changeBottom(value){state.bottom=value;syncUI(state);renderBottom(state);$('.bottom-panel').classList.remove('collapsed');}
function setRunning(value){if(state.loading||!state.engine)return;state.running=value;if(value&&state.iteration>=state.case.solver.target)state.case.solver.target=state.iteration+20000;refresh(false);renderRibbon(state);status(value?'Calculating transient flow':'Calculation paused');}
function resetDiagnostics(){state.records=[];state.diag=null;state.snapshotIteration=0;state.iteration=0;state.steadyCount=0;state.lastConvergenceIteration=0;lastSnapshot=0;lastPerfIteration=0;lastPerf=performance.now();frames=0;view.reset();}
async function loadCase(input,{run=true,forceCPU=false,fit=false}={}){
  const c=validateCase(input),generation=++state.generation;state.running=false;state.loading=true;state.busy=false;snapshotPending=false;
  state.renderer?.destroy();state.renderer=null;state.engine?.destroy();state.engine=null;view.resetCanvas();const targetCanvas=view.canvas;
  state.case=c;state.p=parameters(c);state.mask=rasterize(c,state.p);resetDiagnostics();state.field=null;state.backend='Initializing';if(fit)view.fit();refresh();
  log(`Initializing ${state.p.nx} × ${state.p.ny} lattice; Re=${number(state.p.Re)}, τ+=${state.p.tau.toFixed(6)}.`);
  let engine=null,renderer=null,backend;
  try{
    if(forceCPU||query.has('cpu'))throw new Error('CPU reference backend selected.');
    engine=await GPUSolver.create(state.p,state.mask,error=>{if(generation!==state.generation)return;log(error,'error');toast('The GPU was lost. Restarting this case on the CPU reference solver.','warning');loadCase(state.case,{run:false,forceCPU:true}).catch(fatal);});
    renderer=await engine.makeRenderer(targetCanvas);backend='WebGPU';
  }catch(e){engine?.destroy();if(generation!==state.generation)return;log(e.message,'warn');view.resetCanvas();try{engine=await WorkerSolver.create(state.p,state.mask);backend='CPU · Worker';}catch(workerError){log(workerError.message+' Using cooperative CPU execution.','warn');engine=new CooperativeSolver(state.p,state.mask);backend='CPU · Cooperative';}}
  if(generation!==state.generation){renderer?.destroy();engine.destroy();return;}
  state.engine=engine;state.renderer=renderer;state.backend=backend;state.field=engine.initial;state.loading=false;state.diag=diagnose(state.field,null,state.p,0);state.running=run;
  $('#engine-name').textContent=backend==='WebGPU'?'WebGPU accelerated':'CPU reference solver';$('#engine-badge').textContent=backend==='WebGPU'?'COMPUTE':backend.includes('Worker')?'WORKER':'INLINE';$('#engine-detail').textContent=backend==='WebGPU'?'GPU-resident simulation and scalar rendering. No runtime dependencies.':backend.includes('Worker')?'WebGPU is unavailable. Simulation runs in a dedicated worker.':'GPU and workers are unavailable here. The reference solver yields between steps.';
  $('#dimension-badge').textContent=`2D · ${c.solver.collision.toUpperCase()} · Float32`;
  log(`${backend} ready. D2Q9 ${c.solver.collision.toUpperCase()}; Δt=${number(state.p.dt)} s. Case data stays on this device.`,'success');status(run?'Calculating transient flow':'Ready');persist();refresh();
}
function fatal(e){console.error(e);state.running=false;state.loading=false;log(e.message??String(e),'error');toast(e.message??String(e),'error');syncUI(state);status('Operation failed; see console');}
function receiveSnapshot(result,generation){if(generation!==state.generation)return;if(result.iteration<=state.snapshotIteration&&state.diag){state.field=result.field;return;}const previous=state.field,previousIteration=state.snapshotIteration;state.field=result.field;state.snapshotIteration=result.iteration;
  const d=diagnose(result.field,previous,state.p,result.iteration,previousIteration);state.diag=d;
  if(d.residual&&result.iteration>previousIteration){state.records.push(d);if(state.records.length>3000)state.records.splice(0,500);}
  if(d.unstable){setRunning(false);toast('Numerical stability limit exceeded. Lower the inlet speed, increase viscosity, or refine the mesh.','error');log(`Stopped: min/max density=${number(d.minRho)}/${number(d.maxRho)}, maximum lattice speed=${number(d.maxU)}.`,'error');}
  if(state.case.solver.autoStop&&d.residual&&result.iteration-state.lastConvergenceIteration>=100){state.lastConvergenceIteration=result.iteration;state.steadyCount=result.iteration>1000&&Math.max(d.residual.x,d.residual.y)<state.case.solver.tolerance?state.steadyCount+1:0;if(state.steadyCount>=8){setRunning(false);log('Temporal convergence criterion held for 8 spaced samples. This is not independent validation of the solution.','success');toast('Temporal convergence criterion reached. Calculation paused.');}}
}
async function takeSnapshot(){if(!state.engine)return;if(snapshotPending)return snapshotPending;const generation=state.generation,engine=state.engine;snapshotPending=engine.snapshot();try{const r=await snapshotPending;receiveSnapshot(r,generation);}catch(e){if(generation===state.generation)fatal(e);}finally{if(generation===state.generation)snapshotPending=false;}}
async function advance(steps){if(state.busy||state.loading||!state.engine)return;const generation=state.generation,engine=state.engine;state.busy=true;
  try{const result=await engine.step(steps);if(engine instanceof GPUSolver)await engine.device.queue.onSubmittedWorkDone();if(generation!==state.generation)return;state.iteration=engine.iteration;
    if(result?.field)receiveSnapshot(result,generation);
    else if(performance.now()-lastSnapshot>200){lastSnapshot=performance.now();void takeSnapshot();}
    if(state.iteration>=state.case.solver.target&&state.running){setRunning(false);log(`Target iteration ${state.iteration.toLocaleString()} reached.`,'success');void takeSnapshot();}
  }catch(e){if(generation===state.generation)fatal(e);}finally{if(generation===state.generation)state.busy=false;}
}
function frame(time){requestAnimationFrame(frame);if(state.field&&!state.loading){try{view.draw();}catch(e){setRunning(false);console.error(e);}}
  if(state.running&&!state.busy&&!document.hidden)void advance(Math.max(1,Math.min(state.case.solver.batch,state.case.solver.target-state.iteration)));
  frames++;if(time-lastPerf>1000){const dt=(time-lastPerf)/1000;$('#status-fps').textContent=`${Math.round(frames/dt)} fps`;$('#status-mlups').textContent=`${Math.max(0,(state.iteration-lastPerfIteration)*state.p.n/1e6/dt).toFixed(1)} MLUPS`;lastPerfIteration=state.iteration;lastPerf=time;frames=0;}
  if(time-lastStats>240&&state.field){syncUI(state);renderBottom(state);updateLegend();lastStats=time;}
}
function getPath(obj,path){return path.split('.').reduce((o,k)=>o?.[k],obj);}
function putPath(obj,path,value){const keys=path.split('.'),last=keys.pop();let current=obj;for(const key of keys){if(key==='__proto__'||key==='constructor'||key==='prototype')throw new Error('Invalid settings path');current=current[key];}current[last]=value;}
function physicalSignature(c){return JSON.stringify([c.domain,c.fluid,c.flow,c.solver.collision,c.bodies]);}
async function applySettings(){const next=clone(state.case);for(const el of $('#inspector').querySelectorAll('[data-config]')){
    let path=el.dataset.config;if(path==='fluid.preset')continue;
    let val=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value)/Number(el.dataset.scale??1):el.value;
    if(path==='solver.batch')val=Number(val);
    if(path.startsWith('body.')){const b=next.bodies.find(b=>b.id===state.selected);if(!b)continue;const key=path.slice(5);if(b.type==='polygon'&&(key==='width'||key==='height')){const index=key==='width'?0:1,ratio=val/b[key];b.points=b.points.map(p=>p.map((n,i)=>i===index?n*ratio:n));}b[key]=val;}
    else putPath(next,path,val);
  }
  for(const b of next.bodies)if(b.type==='airfoil')b.height=b.width*b.thickness;
  next.fluid.name=$('[data-config="fluid.preset"]')?({water:'Water · 20 °C',air:'Air · 20 °C',glycerol:'Glycerol · reference',custom:'Custom fluid'}[$('[data-config="fluid.preset"]').value]):next.fluid.name;
  const checked=validateCase(next);state.history.push(state.case);
  if(physicalSignature(checked)!==physicalSignature(state.case)){const run=state.running;await loadCase(checked,{run});toast('Case settings applied. The solution has been reinitialized.');}else{state.case=checked;persist();refresh();toast('Settings applied.');}
}
async function mutateCase(change,{reset=true,fit=false,run=state.running}={}){const next=clone(state.case);change(next);const valid=validateCase(next);state.history.push(state.case);if(reset)await loadCase(valid,{run,fit});else{state.case=valid;persist();refresh();}}
function download(name,content,type='application/octet-stream'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function fileName(ext){return state.case.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+ext;}
async function latest(){const was=state.running;setRunning(false);while(state.busy)await new Promise(r=>setTimeout(r,10));if(snapshotPending)await snapshotPending;const result=await state.engine.snapshot();receiveSnapshot(result,state.generation);return {result,was};}
async function exportField(kind){status('Preparing field export…');const {result,was}=await latest();try{download(fileName(kind==='vtk'?'.vtk':'.csv'),kind==='vtk'?fieldVTK(result.field,state.p):fieldCSV(result.field,state.p),kind==='vtk'?'application/octet-stream':'text/csv');log(`Exported ${state.p.n.toLocaleString()} cells as ${kind.toUpperCase()} at iteration ${result.iteration}.`);toast('Field exported in SI units.');}finally{setRunning(was);}}
function csvCell(v){return '"'+String(v).replaceAll('"','""')+'"';}
function exportProbes(){const header='probe,iteration,time_s,x_m,y_m,velocity_x_m_s,velocity_y_m_s,speed_m_s,gauge_pressure_Pa,solid';const rows=state.case.probes.map(pr=>{const v=sample(state.field,state.p,pr.x,pr.y);return [csvCell(pr.name),state.snapshotIteration,state.snapshotIteration*state.p.dt,pr.x,pr.y,v?.ux??'',v?.uy??'',v?.speed??'',v?.pressure??'',v?.solid?1:0].join(',');});download(fileName('-probes.csv'),[header,...rows].join('\n'),'text/csv');}
function exportMonitors(){const rows=['iteration,time_s,temporal_density_change,temporal_u_change,temporal_v_change,maximum_mach,mean_lattice_density,inlet_outlet_flux_mismatch_percent',...state.records.filter(r=>r.residual).map(r=>[r.iteration,r.iteration*state.p.dt,r.residual.density,r.residual.x,r.residual.y,r.mach,r.meanRho,r.imbalance].join(','))];download(fileName('-monitors.csv'),rows.join('\n'),'text/csv');}
function report(){return {name:state.case.name,created:new Date().toISOString(),case:state.case,backend:state.backend,parameters:state.p,iteration:state.snapshotIteration,time:state.snapshotIteration*state.p.dt,diagnostics:state.diag,scope:'2D isothermal low-Mach weakly compressible D2Q9 TRT/BGK. Temporal residuals, not algebraic finite-volume residuals. No validated engineering accuracy claim.'};}
async function screenshot(){const {was}=await latest();try{view.draw();if(state.engine instanceof GPUSolver)await state.engine.device.queue.onSubmittedWorkDone();const canvas=document.createElement('canvas');canvas.width=view.canvas.width;canvas.height=view.canvas.height;const ctx=canvas.getContext('2d');ctx.drawImage(view.canvas,0,0);ctx.drawImage(view.overlay,0,0);const d=view.dpr;ctx.scale(d,d);ctx.font='600 15px Inter,sans-serif';ctx.fillStyle='#dbe4f0';ctx.fillText('FLUXLAB  /  '+state.case.name,22,29);ctx.font='10px monospace';ctx.fillStyle='#8da1bb';ctx.fillText(`${FIELDS[state.case.display.field].label} [${FIELDS[state.case.display.field].unit}]  ·  iteration ${state.snapshotIteration}  ·  Re ${number(state.p.Re)}`,22,49);const [lo,hi]=view.getRange();const gradient=ctx.createLinearGradient(0,280,0,110);PALETTES[state.case.display.palette].forEach((color,i)=>gradient.addColorStop(i/5,`rgb(${color.map(v=>v*255).join(',')})`));ctx.fillStyle=gradient;ctx.fillRect(view.width-53,110,10,170);ctx.font='8px monospace';ctx.fillStyle='#bdccde';ctx.textAlign='right';for(let i=0;i<6;i++)ctx.fillText(number(hi-(hi-lo)*i/5),view.width-60,113+170*i/5);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Could not encode image');download(fileName('.png'),blob);toast('Viewport image exported.');}finally{setRunning(was);}}
function modal(title,subtitle,body,footer=''){const el=$('#modal');$('#modal-content').innerHTML=`<div class="modal-header"><div><h2>${title}</h2><p>${subtitle}</p></div><button data-action="close-modal" aria-label="Close dialog">×</button></div>${body}${footer?`<div class="modal-footer">${footer}</div>`:''}`;if(!el.open)el.showModal();}
function gallery(){modal('A new perspective on flow.','Start with an example, then make it your own.',`<div class="gallery-grid">${PRESETS.map(p=>`<button class="preset-card" data-preset="${p.id}"><div class="preset-illustration">${icon(p.icon)}</div><div class="preset-text"><h3>${p.title}</h3><span>${p.subtitle}</span><p>${p.description}</p></div></button>`).join('')}</div>`,`<span>Real, local flow calculations. Switching examples replaces the active case.<br>Saved case definitions can be reopened at any time.</span><button data-action="open">Open a case</button>`);}
function files(){modal('Your simulation workspace.','Save, reopen, and exchange cases and measured fields.',`<div class="file-actions">${[['save','Save case','save','Geometry, materials, numerical settings, display and probes.'],['open','Open case','folder','Restore a FluxLab JSON case definition.'],['csv','Export field CSV','download','All lattice nodes, velocity, pressure, and solid mask.'],['vtk','Export field VTK','cube','Structured grid for ParaView and compatible postprocessors.'],['screenshot','Export image','camera','Capture the active viewport and scientific color legend.'],['gallery','Example library','layers','Six editable, real-solver starter configurations.']].map(([a,t,i,d])=>`<button data-action="${a}">${icon(i)}<div><strong>${t}</strong><small>${d}</small></div></button>`).join('')}</div>`,`<span>Case files contain definitions, not resumable solver populations.<br>No Ansys CAS/DAT/MSH import is implemented.</span><button data-action="close-modal">Done</button>`);}
function help(){modal('Built to explore. Open to inspect.','FluxLab 1.0 · An independent browser CFD workbench.',`<div class="help-grid"><div><h3>A working numerical core</h3><p>D2Q9 lattice Boltzmann with TRT or BGK collision, pull streaming, link bounce-back walls, and Zou–He inlet / pressure outlet reconstruction. Physical viscosity, time, velocity and gauge pressure are explicitly mapped to SI units.</p><h3>Workflow</h3><p>Create or import geometry, choose a fluid and mesh, initialize, calculate, then inspect contours and probes. Case changes reset the field. Display changes do not.</p><h3>Source documentation</h3><p><a href="./docs/NUMERICS.md" target="_blank" rel="noopener">Numerical method and limits ↗</a><br><a href="./README.md" target="_blank" rel="noopener">Architecture and local setup ↗</a></p></div><div><h3>Keyboard shortcuts</h3>${[['Space','Run / pause'],['F','Fit domain'],['V / H','Select / pan'],['C / R','Circle / rectangle'],['P','Place a probe'],['M','Toggle mesh'],['Delete','Delete selected body'],['Ctrl / ⌘ Z','Undo'],['Ctrl / ⌘ Shift Z','Redo'],['Ctrl / ⌘ S','Save case'],['Ctrl / ⌘ O','Open case'],['Enter','Finish polygon'],['Escape','Cancel editing / close panel']].map(([k,t])=>`<div class="shortcut-row"><span>${t}</span><kbd>${k}</kbd></div>`).join('')}</div></div><div class="danger-note">Scope: 2D, isothermal, laminar, low-Mach flow on a uniform Cartesian lattice. Not a validated substitute for Ansys Fluent, not 3D, and not for safety-critical design decisions. The UI follows a familiar CFD workflow; no Ansys code or branding is used.</div>`);}
function setTool(tool){state.tool=tool;polygonPoints=[];view.draft=null;const hints={circle:'Drag from the center to create a cylinder. Esc cancels.',box:'Drag opposite corners to create a rectangle. Esc cancels.',polygon:'Click vertices. Press Enter or double-click to close. Esc cancels.',probe:'Click a fluid cell to place a measurement probe.',pan:'Drag to pan. Scroll to zoom. F fits the domain.'};$('#edit-hint').textContent=hints[tool]??'';$('#edit-hint').hidden=!hints[tool];view.overlay.style.cursor=tool==='pan'?'grab':tool==='select'?'default':'crosshair';syncUI(state);}
async function addBody(type){let newID;await mutateCase(c=>{const L=c.domain.length,H=c.domain.height,w=type==='airfoil'?L*.22:Math.min(L,H)*.17;newID=uid();c.bodies.push({id:newID,type,name:`${type==='circle'?'cylinder':type}-${c.bodies.length+1}`,x:L*.4,y:H*.5,width:w,height:type==='airfoil'?w*.12:w,angle:type==='airfoil'?-8:0,...(type==='airfoil'?{thickness:.12}:{})});});state.selected=newID;showPanel('body',newID);}
async function deleteBody(){if(!state.selected){toast('Select a body first.','warning');return;}const id=state.selected;state.selected=null;await mutateCase(c=>c.bodies=c.bodies.filter(b=>b.id!==id));showPanel('geometry');}
async function duplicate(){const b=state.case.bodies.find(b=>b.id===state.selected);if(!b){toast('Select a body to duplicate.','warning');return;}const copy=clone(b);copy.id=uid();copy.name+='-copy';copy.x+=state.p.dx*8;copy.y+=state.p.dx*8;await mutateCase(c=>c.bodies.push(copy));state.selected=copy.id;showPanel('body',copy.id);}
function checkCase(){validateCase(state.case);const p=state.p,mask=rasterize(state.case,p);let solid=0;for(const m of mask)if(m)solid++;const warnings=[];for(const b of state.case.bodies){if(Math.min(b.width,b.height)/p.dx<4)warnings.push(`${b.name} is fewer than four cells thick.`);}if(state.diag?.mach>.25)warnings.push('Maximum lattice Mach exceeds 0.25.');if(solid/p.n>.7)warnings.push('More than 70% of the domain is solid.');if(p.tau<.52)warnings.push('Viscous relaxation is close to its stability limit.');const msg=`Mesh: ${p.nx} × ${p.ny}; ${p.n-solid} fluid cells; Δx=${number(p.dx)} m; τ+=${p.tau.toFixed(5)}.`;log(msg,'success');for(const w of warnings)log(w,'warn');toast(warnings.length?msg+' '+warnings.join(' '):'Case and mesh checks passed. '+msg,warnings.length?'warning':'success');}
async function resolution(nx){await mutateCase(c=>c.domain.nx=nx);showPanel('mesh');toast(`Regenerated ${state.p.nx} × ${state.p.ny} lattice.`);}
async function action(name){
  switch(name){
    case 'run':setRunning(!state.running);break;case 'step':setRunning(false);await advance(1);await takeSnapshot();refresh(false);break;
    case 'initialize':await loadCase(state.case,{run:false});toast('Solution initialized from the prescribed equilibrium field.');break;
    case 'gallery':gallery();break;case 'files':files();break;case 'close-modal':$('#modal').close();break;case 'help':help();break;
    case 'save':persist();download(fileName('.fluxlab.json'),JSON.stringify(state.case,null,2),'application/json');toast('Case saved.');break;
    case 'open':$('#modal').close();$('#case-file').click();break;
    case 'rename':modal('Name your case.','A descriptive name keeps your workspace organized.',`<form id="rename-form" class="modal-form"><label>Case name<input id="rename-input" required maxlength="120" value="${esc(state.case.name)}"></label><button type="submit" class="run-main">Save name</button></form>`);$('#rename-input').focus();$('#rename-input').select();break;
    case 'apply':await applySettings();break;case 'apply-display':await applySettings();break;
    case 'general':showPanel('general');break;case 'geometry':showPanel('geometry');break;case 'mesh':showPanel('mesh');break;case 'models':showPanel('models');break;case 'materials':showPanel('materials');break;case 'boundary':showPanel('boundary');break;case 'inlet':showPanel('inlet');break;case 'outlet':showPanel('outlet');break;case 'walls':showPanel('walls');break;case 'solution':showPanel('solution');break;
    case 'contours':showPanel('results','contours');break;case 'probes':showPanel('probes');changeBottom('probes');break;case 'report':showPanel('report');changeBottom('report');break;case 'monitors':changeBottom('convergence');showPanel('solution','monitors');break;
    case 'velocity':state.case.display.field='speed';showPanel('results');persist();refresh();break;case 'pressure':state.case.display.field='pressure';state.case.display.palette='diverging';showPanel('results');persist();refresh();break;case 'vorticity':state.case.display.field='vorticity';state.case.display.palette='diverging';showPanel('results');persist();refresh();break;
    case 'toggle-mesh':case 'toggle-streamlines':case 'toggle-vectors':case 'toggle-particles':{const k=name.slice(7);state.case.display[k]=!state.case.display[k];persist();refresh();break;}
    case 'add-circle':await addBody('circle');break;case 'add-airfoil':await addBody('airfoil');break;case 'draw-circle':setTool('circle');break;case 'draw-box':setTool('box');break;case 'draw-polygon':setTool('polygon');break;case 'probe-tool':setTool('probe');break;case 'select':setTool('select');break;case 'pan':setTool('pan');break;
    case 'duplicate':await duplicate();break;case 'delete':await deleteBody();break;
    case 'undo':{const c=state.history.undo(state.case);if(c){state.selected=null;await loadCase(c,{run:state.running});toast('Undone. Solution reinitialized.');}else toast('Nothing to undo.','warning');break;}
    case 'redo':{const c=state.history.redo(state.case);if(c){state.selected=null;await loadCase(c,{run:state.running});toast('Redone. Solution reinitialized.');}else toast('Nothing to redo.','warning');break;}
    case 'coarse':await resolution(192);break;case 'medium':await resolution(384);break;case 'fine':await resolution(768);break;case 'check':checkCase();break;
    case 'fit':view.fit();break;case 'zoom-in':view.zoomAt(view.width/2,view.height/2,1.25);break;case 'zoom-out':view.zoomAt(view.width/2,view.height/2,.8);break;
    case 'theme':{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';try{localStorage.setItem('fluxlab-theme',dark?'light':'dark');}catch{}refresh(false);break;}
    case 'toggle-bottom':$('.bottom-panel').classList.toggle('collapsed');break;case 'fullscreen':if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen();break;
    case 'screenshot':await screenshot();break;case 'csv':await exportField('csv');break;case 'vtk':await exportField('vtk');break;case 'export-monitor':exportMonitors();break;case 'export-probes':exportProbes();break;case 'export-report':download(fileName('-report.json'),JSON.stringify(report(),null,2),'application/json');break;
    case 'clear-probes':await mutateCase(c=>c.probes=[],{reset:false});break;case 'import-geometry':$('#geometry-file').click();break;
    case 'expand-tree':state.folded.clear();renderTree(state);break;case 'graphics':$('.inspector-pane').classList.remove('mobile-open');break;
    default:log(`Unknown action: ${name}`,'warn');
  }
}
function nodeClick(id){const b=state.case.bodies.find(b=>b.id===id);if(b){state.selected=b.id;showPanel('body',id);return;}const map={case:'general',setup:'models',methods:'models',initialization:'solution',run:'solution',monitors:'solution',results:'results',contours:'results',vectors:'results',streamlines:'results'};showPanel(map[id]??id,id);if(id==='monitors')changeBottom('convergence');if(id==='probes')changeBottom('probes');if(id==='report')changeBottom('report');if(id==='vectors'||id==='streamlines'){state.case.display[id]=true;syncUI(state);renderInspector(state);}}
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-action],[data-tab],[data-bottom],[data-node],[data-tool],[data-toggle],[data-preset],[data-res],[data-delete-probe],[data-fold]');if(!el)return;
  if(el.dataset.fold){state.folded.has(el.dataset.fold)?state.folded.delete(el.dataset.fold):state.folded.add(el.dataset.fold);renderTree(state);return;}
  if(el.dataset.action){action(el.dataset.action).catch(fatal);return;}
  if(el.dataset.tab){state.ribbonTab=el.dataset.tab;renderRibbon(state);syncUI(state);if(el.dataset.tab!=='home'&&el.dataset.tab!=='view')showPanel(el.dataset.tab==='setup'?'models':el.dataset.tab);return;}
  if(el.dataset.bottom){changeBottom(el.dataset.bottom);return;}
  if(el.dataset.node){nodeClick(el.dataset.node);return;}
  if(el.dataset.tool){setTool(el.dataset.tool);return;}
  if(el.dataset.toggle){const k=el.dataset.toggle;state.case.display[k]=!state.case.display[k];persist();refresh();return;}
  if(el.dataset.res){resolution(Number(el.dataset.res)).catch(fatal);return;}
  if(el.dataset.deleteProbe){mutateCase(c=>c.probes=c.probes.filter(p=>p.id!==el.dataset.deleteProbe),{reset:false}).catch(fatal);return;}
  if(el.dataset.preset){$('#modal').close();state.history.push(state.case);state.selected=null;state.panel='solution';state.node='run';loadCase(preset(el.dataset.preset),{run:true,fit:true}).catch(fatal);}
});
document.addEventListener('submit',e=>{if(e.target.id==='rename-form'){e.preventDefault();const name=$('#rename-input').value.trim();if(name){state.case.name=name;persist();refresh();$('#modal').close();}}});
$('#tree-search').addEventListener('input',()=>renderTree(state));
$('#field-select').addEventListener('change',e=>{state.case.display.field=e.target.value;if(['pressure','vorticity','uy'].includes(e.target.value))state.case.display.palette='diverging';persist();refresh();});
$('#inspector').addEventListener('change',e=>{const path=e.target.dataset.config;if(path==='fluid.preset'){const presets={water:[998.2,.001002],air:[1.204,1.825e-5],glycerol:[1260,1.49]};const v=presets[e.target.value];if(v){$('[data-config="fluid.density"]').value=v[0];$('[data-config="fluid.viscosity"]').value=v[1];}}
  else if(path?.startsWith('display.')&&(e.target.type==='checkbox'||e.target.tagName==='SELECT')){putPath(state.case,path,e.target.type==='checkbox'?e.target.checked:e.target.value);persist();syncUI(state);updateLegend();}
});
$('#case-file').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20e6)throw new Error('Case file exceeds the 20 MB limit.');const c=validateCase(JSON.parse(await f.text()));state.history.push(state.case);state.selected=null;state.panel='solution';await loadCase(c,{run:false,fit:true});toast('Case loaded and initialized. Press Space to calculate.');}catch(err){fatal(err);}finally{e.target.value='';}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});
// Geometry editor: pointer transactions commit once, so undo restores the complete prior case.
function point(e){const r=view.overlay.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
view.overlay.addEventListener('pointerdown',e=>{
  if(state.loading||e.button>1)return;$('.inspector-pane').classList.remove('mobile-open');const [x,y]=point(e),world=view.world(x,y);view.overlay.setPointerCapture(e.pointerId);$('#probe-tooltip').hidden=true;
  if(e.button===1||state.tool==='pan'||e.altKey){drag={type:'pan',start:[x,y],pan:[...view.pan]};return;}
  if(world[0]<0||world[1]<0||world[0]>state.case.domain.length||world[1]>state.p.actualHeight)return;
  if(state.tool==='select'){const hit=[...state.case.bodies].reverse().find(b=>contains(outline(b),...world));if(hit){state.selected=hit.id;showPanel('body',hit.id);$('.inspector-pane').classList.remove('mobile-open');wasRunning=state.running;setRunning(false);drag={type:'body',id:hit.id,start:world,origin:[hit.x,hit.y],before:clone(state.case),moved:false};}else{state.selected=null;renderTree(state);}return;}
  if(state.tool==='circle'||state.tool==='box'){drag={type:'draw',shape:state.tool,start:world};view.draft={type:state.tool,points:[world,world]};return;}
  if(state.tool==='polygon'){polygonPoints.push(world);view.draft={type:'polygon',points:polygonPoints};return;}
  if(state.tool==='probe'){state.case.probes.push({id:uid(),name:`P${state.case.probes.length+1}`,x:world[0],y:world[1]});persist();changeBottom('probes');renderTree(state);if(state.panel==='probes')renderInspector(state);toast(`Probe ${state.case.probes.at(-1).name} placed.`);}
});
view.overlay.addEventListener('pointermove',e=>{if(!state.p)return;const [x,y]=point(e),world=view.world(x,y);$('#coordinates').textContent=`x ${(world[0]*1000).toFixed(2)} · y ${(world[1]*1000).toFixed(2)} mm`;
  if(drag?.type==='pan'){view.pan=[drag.pan[0]+x-drag.start[0],drag.pan[1]+y-drag.start[1]];return;}
  if(drag?.type==='body'){const b=state.case.bodies.find(b=>b.id===drag.id);b.x=clamp(drag.origin[0]+world[0]-drag.start[0],0,state.case.domain.length);b.y=clamp(drag.origin[1]+world[1]-drag.start[1],0,state.p.actualHeight);drag.moved ||= Math.hypot(b.x-drag.origin[0],b.y-drag.origin[1])>state.p.dx*.15;return;}
  if(drag?.type==='draw'){view.draft.points[1]=[clamp(world[0],0,state.case.domain.length),clamp(world[1],0,state.p.actualHeight)];return;}
  if(state.tool==='polygon'&&polygonPoints.length){view.draft={type:'polygon',points:[...polygonPoints,world]};return;}
  if(state.tool==='probe'&&state.field){const v=sample(state.field,state.p,...world),tip=$('#probe-tooltip');if(v&&!v.solid){tip.hidden=false;tip.style.left=`${Math.min(x+18,view.width-165)}px`;tip.style.top=`${Math.max(60,Math.min(y+16,view.height-100))}px`;tip.innerHTML=`<strong>Local field sample</strong><br>|u| ${number(v.speed)} m/s<br>p ${number(v.pressure)} Pa`;}else tip.hidden=true;}
});
async function finishPointer(e){if(!drag)return;const d=drag;drag=null;try{if(d.type==='body'){if(d.moved){const edited=validateCase(state.case);state.history.push(d.before);await loadCase(edited,{run:wasRunning});renderInspector(state);}else setRunning(wasRunning);}
  else if(d.type==='draw'){const points=view.draft.points;view.draft=null;const [a,b]=points;let w=Math.abs(b[0]-a[0]),h=Math.abs(b[1]-a[1]),x=(a[0]+b[0])/2,y=(a[1]+b[1])/2;if(d.shape==='circle'){w=h=2*Math.hypot(b[0]-a[0],b[1]-a[1]);x=a[0];y=a[1];}if(w<state.p.dx*2||h<state.p.dx*2){toast('Draw a body at least two cells across.','warning');return;}const id=uid();await mutateCase(c=>c.bodies.push({id,name:`${d.shape==='circle'?'cylinder':'rectangle'}-${c.bodies.length+1}`,type:d.shape,x,y,width:w,height:h,angle:0}));state.selected=id;setTool('select');showPanel('body',id);}}
  catch(err){if(d.before)state.case=d.before;fatal(err);}}
view.overlay.addEventListener('pointerup',e=>void finishPointer(e));
view.overlay.addEventListener('pointercancel',()=>{if(drag?.before)state.case=drag.before;drag=null;view.draft=null;});
view.overlay.addEventListener('pointerleave',()=>{$('#probe-tooltip').hidden=true;});
view.overlay.addEventListener('wheel',e=>{e.preventDefault();const [x,y]=point(e);view.zoomAt(x,y,Math.exp(-e.deltaY*.001));},{passive:false});
view.overlay.addEventListener('dblclick',()=>{if(state.tool==='polygon')finishPolygon().catch(fatal);});
async function finishPolygon(){if(polygonPoints.length<3){toast('A polygon needs at least three vertices.','warning');return;}const pts=polygonPoints.filter((p,i)=>!i||Math.hypot(p[0]-polygonPoints[i-1][0],p[1]-polygonPoints[i-1][1])>state.p.dx*.1);if(pts.length<3)return;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),x=(minx+maxx)/2,y=(miny+maxy)/2;const id=uid();await mutateCase(c=>c.bodies.push({id,type:'polygon',name:`polygon-${c.bodies.length+1}`,x,y,width:maxx-minx,height:maxy-miny,angle:0,points:pts.map(p=>[p[0]-x,p[1]-y])}));setTool('select');state.selected=id;showPanel('body',id);}
document.addEventListener('keydown',e=>{const inInput=e.target.matches('input,textarea,select');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();action('save').catch(fatal);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();action('open').catch(fatal);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#tree-search').focus();return;}if(inInput)return;
  if(e.key==='Escape'){if(drag?.before)state.case=drag.before;drag=null;setTool('select');$('.inspector-pane').classList.remove('mobile-open');$('#probe-tooltip').hidden=true;return;}if($('#modal').open)return;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo').catch(fatal);return;}
  if(e.key===' '){e.preventDefault();action('run').catch(fatal);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();action('delete').catch(fatal);}else if(e.key==='Enter'&&state.tool==='polygon'){finishPolygon().catch(fatal);}else{const k=e.key.toLowerCase(),map={f:'fit',m:'toggle-mesh',v:'select',h:'pan',c:'draw-circle',r:'draw-box',p:'probe-tool'};if(map[k]){e.preventDefault();action(map[k]).catch(fatal);}}
});
// SVG input is parsed but never injected as active content. Only geometric attributes are copied.
$('#geometry-file').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>4e6)throw new Error('Geometry file exceeds the 4 MB limit.');const text=await f.text();let bodies;
    if(f.name.toLowerCase().endsWith('.json')){const parsed=JSON.parse(text);bodies=Array.isArray(parsed)?parsed:parsed.bodies;if(!Array.isArray(bodies))throw new Error('Geometry JSON must contain an array of FluxLab bodies.');bodies=bodies.map(b=>({...b,id:uid()}));}
    else bodies=importSVG(text);
    if(!bodies.length)throw new Error('No supported closed geometry was found.');await mutateCase(c=>c.bodies.push(...bodies));showPanel('geometry');toast(`Imported ${bodies.length} solid bodies.`);
  }catch(err){fatal(err);}finally{e.target.value='';}});
function importSVG(text){const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw new Error('Invalid SVG.');const paths=[];const num=(el,k,d=0)=>parseFloat(el.getAttribute(k)??d);const nodes=[...doc.querySelectorAll('path,polygon,rect,circle,ellipse')];if(nodes.length>128)throw new Error('SVG has more than 128 primitive shapes.');
  for(const el of nodes){let pts=[];const type=el.localName;if(type==='rect'){const x=num(el,'x'),y=num(el,'y'),w=num(el,'width'),h=num(el,'height');pts=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];}
    if(type==='circle'||type==='ellipse'){const x=num(el,'cx'),y=num(el,'cy'),rx=type==='circle'?num(el,'r'):num(el,'rx'),ry=type==='circle'?num(el,'r'):num(el,'ry');for(let i=0;i<96;i++){const t=i*Math.PI/48;pts.push([x+rx*Math.cos(t),y+ry*Math.sin(t)]);}}
    if(type==='polygon'){const list=(el.getAttribute('points')??'').trim().split(/[\s,]+/).map(Number);for(let i=0;i<list.length-1;i+=2)pts.push([list[i],list[i+1]]);}
    if(type==='path'){const d=el.getAttribute('d')??'';if(!/[zZ]\s*$/.test(d)){log('Skipped open SVG path. Only closed paths become solid bodies.','warn');continue;}if((d.match(/[mM]/g)??[]).length>1){log('Skipped compound SVG path. Holes and multiple subpaths are not supported.','warn');continue;}const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);const length=path.getTotalLength();if(!Number.isFinite(length)||length===0)continue;for(let i=0;i<256;i++){const p=path.getPointAtLength(length*i/256);pts.push([p.x,p.y]);}}
    if(el.closest('[transform]'))throw new Error('SVG transforms must be flattened before import. Export with transforms applied.');
    if(pts.length>2&&pts.every(p=>p.every(Number.isFinite)))paths.push(pts);
  }
  if(!paths.length)return [];const all=paths.flat(),minx=Math.min(...all.map(p=>p[0])),maxx=Math.max(...all.map(p=>p[0])),miny=Math.min(...all.map(p=>p[1])),maxy=Math.max(...all.map(p=>p[1]));const scale=Math.min(state.case.domain.length*.45/Math.max(maxx-minx,1e-9),state.case.domain.height*.55/Math.max(maxy-miny,1e-9));
  return paths.map((pts,i)=>{const mapped=pts.map(([x,y])=>[(x-(minx+maxx)/2)*scale+state.case.domain.length*.45,((miny+maxy)/2-y)*scale+state.case.domain.height*.5]),xs=mapped.map(p=>p[0]),ys=mapped.map(p=>p[1]),x=(Math.min(...xs)+Math.max(...xs))/2,y=(Math.min(...ys)+Math.max(...ys))/2;return {id:uid(),type:'polygon',name:`imported-${i+1}`,x,y,width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys),angle:0,points:mapped.map(p=>[p[0]-x,p[1]-y])};});}
// Narrow diagnostics API for tests and inspection; no network service or telemetry.
window.fluxlab={get state(){return state;},get viewport(){return view;},loadCase,preset,advance,takeSnapshot,action,checkCase,importSVG};
hydrate();try{document.documentElement.dataset.theme=localStorage.getItem('fluxlab-theme')??'light';}catch{}
let first=preset(query.get('case')??'airfoil');if(!query.has('fresh')&&!query.has('case')){try{const saved=localStorage.getItem('fluxlab-case-v1');if(saved)first=validateCase(JSON.parse(saved));}catch{log('Stored case could not be restored; using the airfoil example.','warn');}}
requestAnimationFrame(frame);loadCase(first,{run:!query.has('paused'),fit:true}).catch(fatal);
