import {icon,escapeHTML as esc,hydrate} from './icons.js';
import {FIELDS,formatNumber,drawChart} from './viewport.js';
import {sample} from './diagnostics.js';
const qs=s=>document.querySelector(s);
const button=(action,label,ic,cls='')=>`<button class="ribbon-button ${cls}" data-action="${action}" title="${label}">${icon(ic)}<span>${label}</span></button>`;
const small=(action,label,ic)=>`<button class="ribbon-small" data-action="${action}">${icon(ic)}${label}</button>`;
const group=(label,content)=>`<div class="ribbon-group">${content}<span class="ribbon-group-label">${label}</span></div>`;
const stack=(...rows)=>`<div class="ribbon-stack">${rows.join('')}</div>`;
export function renderRibbon(s){const B=button,S=small,G=group,St=stack;let html='';const run=B('run',s.running?'Pause':'Calculate',s.running?'pause':'play','run');
  const caseGroup=G('Case',B('gallery','New case','file','primary')+St(S('open','Open case','folder'),S('save','Save case','save')));
  const geometry=G('Geometry',B('geometry','Geometry','cube')+St(S('add-circle','Cylinder','circle'),S('add-airfoil','Airfoil','airfoil')));
  const mesh=G('Mesh',B('mesh','Generate','mesh')+St(S('check','Check','check'),S('toggle-mesh','Display mesh','grid')));
  const solve=G('Solution',B('initialize','Initialize','reset')+run+B('step','Step','step'));
  const results=G('Results',B('contours','Contours','contour')+St(S('toggle-vectors','Vectors','vectors'),S('toggle-streamlines','Streamlines','flow')));
  switch(s.ribbonTab){
    case 'home':html=caseGroup+geometry+mesh+G('Physics',B('models','Models','settings')+St(S('materials','Materials','material'),S('boundary','Boundaries','boundary')))+solve+results;break;
    case 'geometry':html=G('Project',B('gallery','Examples','layers')+B('import-geometry','Import','upload'))+G('Create bodies',B('draw-circle','Cylinder','circle')+B('draw-box','Rectangle','box')+B('add-airfoil','Airfoil','airfoil')+B('draw-polygon','Polygon','polygon'))+G('Edit geometry',B('select','Select','cursor')+B('duplicate','Duplicate','duplicate')+B('delete','Delete','trash'))+G('History',B('undo','Undo','undo')+B('redo','Redo','redo'))+G('Domain',B('general','Dimensions','ruler')+B('fit','Fit view','fit'));break;
    case 'mesh':html=G('Mesh operations',B('mesh','Settings','settings')+B('apply','Generate','mesh')+B('check','Check mesh','check'))+G('Refinement',B('coarse','Coarse','grid')+B('medium','Medium','mesh')+B('fine','Fine','layers'))+G('Display',B('toggle-mesh','Show grid','grid')+B('fit','Fit mesh','fit'))+G('Export',B('vtk','VTK field','download')+B('save','Save case','save'));break;
    case 'setup':html=G('General',B('general','Domain','ruler')+B('models','Models','settings'))+G('Physical properties',B('materials','Materials','material')+B('boundary','Boundaries','boundary'))+G('Boundary types',B('inlet','Inlet','arrow')+B('outlet','Outlet','pressure')+B('walls','Walls','box'))+G('Prepare',B('check','Check case','check')+B('initialize','Initialize','reset'));break;
    case 'solution':html=G('Numerics',B('models','Methods','settings')+B('solution','Run controls','cpu'))+solve+G('Monitors',B('monitors','Residuals','chart')+B('probes','Probes','probe')+B('report','Summary','file'))+G('Data',B('export-monitor','Export history','download')+B('save','Save case','save'));break;
    case 'results':html=results+G('Field variables',B('velocity','Velocity','flow')+B('pressure','Pressure','pressure')+B('vorticity','Vorticity','refresh'))+G('Analysis',B('probe-tool','Add probe','probe')+B('probes','Probe data','chart')+B('report','Summary','file'))+G('Export',B('csv','Field CSV','download')+B('vtk','Field VTK','cube')+B('screenshot','Save image','camera'));break;
    case 'view':html=G('Navigation',B('fit','Fit domain','fit')+B('pan','Pan','hand')+B('zoom-in','Zoom in','plus')+B('zoom-out','Zoom out','minus'))+G('Overlays',B('toggle-mesh','Mesh','grid')+B('toggle-streamlines','Streamlines','flow')+B('toggle-vectors','Vectors','vectors')+B('toggle-particles','Tracers','spark'))+G('Workspace',B('theme','Theme','sun')+B('toggle-bottom','Monitors','chart')+B('fullscreen','Fullscreen','maximize'))+G('Capture',B('screenshot','Image','camera'));break;
  }
  html+='<div class="ribbon-tip">'+icon('lightning')+'<span><strong>Compute where you create.</strong><br>Local-first. No cloud queue.</span></div>';qs('#ribbon').innerHTML=html;
}
export function renderTree(s){const rows=[];const filter=(qs('#tree-search').value??'').toLowerCase();const row=(id,name,ic,level=0,extra='',branch=false)=>{if(filter&&!name.toLowerCase().includes(filter))return;rows.push(`<button class="tree-row level-${level} ${(id===s.node||id===s.selected)?'active':''} ${id===s.selected?'selected':''}" data-node="${esc(id)}"><span class="tree-caret" ${branch?`data-fold="${esc(id)}"`:''}>${branch?(s.folded.has(id)?'›':'⌄'):''}</span>${icon(ic)}<span class="tree-name">${esc(name)}</span>${extra}</button>`);};
  const check='<span class="check">✓</span>';
  row('case',s.case.name,'folder',0,'',true);
  if(!s.folded.has('case')||filter){
    row('general','General','settings',1,check);row('geometry','Geometry','cube',1,`<span class="tag">${s.case.bodies.length}</span>`,true);
    if(!s.folded.has('geometry')||filter)for(const b of s.case.bodies)row(b.id,b.name,b.type==='airfoil'?'airfoil':b.type==='circle'?'circle':b.type==='box'?'box':'polygon',2);
    row('mesh','Mesh','mesh',1,check);row('setup','Setup','layers',1,'',true);
    if(!s.folded.has('setup')||filter){row('models','Models','settings',2,check);row('materials','Materials','material',2,check);row('boundary','Boundary conditions','boundary',2,'',true);if(!s.folded.has('boundary')||filter){row('inlet',s.p?.mode===1?'moving-lid':'velocity-inlet','arrow',3);row('outlet',s.p?.mode===1?'fixed-walls':'pressure-outlet','pressure',3);row('walls','wall-surfaces','box',3);}}
    rows.push('<div class="tree-section-divider"></div>');row('solution','Solution','cpu',1,'',true);
    if(!s.folded.has('solution')||filter){row('methods','Solution methods','settings',2);row('initialization','Initialization','reset',2,check);row('monitors','Monitors','chart',2);row('run','Run calculation','play',2);}
    row('results','Results','contour',1,'',true);if(!s.folded.has('results')||filter){row('contours','Contours','contour',2);row('vectors','Vectors','vectors',2);row('streamlines','Streamlines','flow',2);row('probes','Probe points','probe',2,`<span class="tag">${s.case.probes.length}</span>`);row('report','Reports','file',2);}
  }
  qs('#tree').innerHTML=rows.join('');
}
function label(name){return `<div class="section-label">${name}</div>`;}
function input(path,name,val,unit='',scale=1,step='any',type='number'){return `<div class="form-row"><label>${name}</label><div class="input-unit"><input type="${type}" data-config="${path}" data-scale="${scale}" value="${esc(type==='number'?Number((val*scale).toPrecision(10)):val)}" step="${step}" aria-label="${name}">${unit?`<span>${unit}</span>`:''}</div></div>`;}
function select(path,name,val,options){return `<div class="form-row"><label>${name}</label><select data-config="${path}" aria-label="${name}">${options.map(([v,t])=>`<option value="${v}" ${val===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}
function check(path,name,val){return `<label class="check-row"><span>${name}</span><span><input class="sr" type="checkbox" data-config="${path}" ${val?'checked':''}><i class="toggle"></i></span></label>`;}
function hero(ic,title,sub){return `<div class="inspector-hero"><div class="hero-icon">${icon(ic)}</div><div><h2>${title}</h2><p>${sub}</p></div></div>`;}
function secondary(action,title,ic,cls=''){return `<button class="button-secondary ${cls}" data-action="${action}">${icon(ic)}${title}</button>`;}
function stat(name,value){return `<div class="stat-line"><span>${name}</span><strong>${value}</strong></div>`;}
export function renderInspector(s){const c=s.case,p=s.p,d=s.diag,b=c.bodies.find(x=>x.id===s.selected);let html='',heading='Solution setup';const apply=secondary('apply','Apply settings','check','accent');
  switch(s.panel){
    case 'general':heading='General';html=hero('ruler','Computational domain','Planar 2D · SI unit system')+label('Dimensions')+input('domain.length','Length',c.domain.length,'mm',1000)+input('domain.height','Height',c.domain.height,'mm',1000)+input('domain.nx','Cells in X',c.domain.nx,'cells',1,1)+select('flow.mode','Flow configuration',c.flow.mode,[['tunnel','Inlet / pressure outlet'],['cavity','Lid-driven cavity'],['periodic','Fully periodic validation']])+apply+`<p class="form-note">The height is snapped to the nearest square-cell lattice. Applying physical changes reinitializes the solution.</p><div class="stats-card">${stat('Grid height',formatNumber(p.actualHeight*1000)+' mm')}${stat('Cell spacing',formatNumber(p.dx*1000)+' mm')}${stat('Physical time step',formatNumber(p.dt)+' s')}</div>`;break;
    case 'geometry':heading='Geometry';html=hero('cube','Solid bodies','Select in the outline or click a body.')+`<div class="tag-row"><span class="selected">${c.bodies.length} bodies</span><span>No-slip surfaces</span></div>`+c.bodies.map(b=>`<div class="body-list-row" role="button" tabindex="0" data-node="${esc(b.id)}">${icon(b.type==='airfoil'?'airfoil':b.type==='circle'?'circle':b.type==='box'?'box':'polygon')}<span>${esc(b.name)}</span><small>${esc(b.type)}</small></div>`).join('')+label('Create geometry')+secondary('draw-circle','Draw cylinder','circle')+secondary('draw-box','Draw rectangle','box')+secondary('add-airfoil','Add NACA airfoil','airfoil')+secondary('draw-polygon','Draw polygon','polygon')+secondary('import-geometry','Import SVG / geometry JSON','upload')+`<p class="form-note">Drag existing bodies to move them. Set exact dimensions in the body inspector. Any geometry edit regenerates the solid mask and resets the solution.</p>`;break;
    case 'body':heading='Body properties';if(!b){html=hero('cursor','Nothing selected','Select a body in the graphics window.');break;}html=hero(b.type==='airfoil'?'airfoil':b.type==='circle'?'circle':'box',esc(b.name),`${esc(b.type)} · no-slip wall`)+input('body.name','Name',b.name,'',1,'any','text')+label('Position')+'<div class="form-pair">'+input('body.x','X position',b.x,'mm',1000)+input('body.y','Y position',b.y,'mm',1000)+'</div>'+label('Dimensions')+'<div class="form-pair">'+input('body.width',b.type==='airfoil'?'Chord':'Width',b.width,'mm',1000)+input('body.height','Height',b.height,'mm',1000)+'</div>'+input('body.angle','Rotation (counterclockwise)',b.angle,'deg',1,.5)+(b.type==='airfoil'?input('body.thickness','Thickness / chord',b.thickness,'ratio',1,.01):'')+apply+(b.type==='airfoil'?'<p class="form-note">Symmetric NACA four-digit thickness profile. Thickness ratio controls the airfoil; the height is derived from chord × thickness.</p>':'')+label('Actions')+secondary('duplicate','Duplicate body','duplicate')+secondary('delete','Delete body','trash','button-danger');break;
    case 'mesh':heading='Mesh';html=hero('mesh','Cartesian lattice','Uniform square cells · resolved solid mask')+label('Resolution')+`<div class="segmented"><button data-res="192" class="${c.domain.nx===192?'active':''}">Coarse</button><button data-res="384" class="${c.domain.nx===384?'active':''}">Medium</button><button data-res="768" class="${c.domain.nx===768?'active':''}">Fine</button></div><br>`+input('domain.nx','Cells in X',c.domain.nx,'cells',1,1)+apply+check('display.mesh','Display mesh',c.display.mesh)+label('Mesh statistics')+`<div class="stats-card">${stat('Dimensions',`${p.nx} × ${p.ny}`)}${stat('Total cells',p.n.toLocaleString())}${stat('Fluid cells',d?.count?.toLocaleString()??'—')}${stat('Cell size',formatNumber(p.dx*1000)+' mm')}${stat('Core buffer estimate',(p.n*92/1048576).toFixed(1)+' MiB')}</div>`+secondary('check','Check mesh and parameters','check')+'<p class="form-note warning">This is a Cartesian lattice, not an unstructured Fluent mesh. Curved walls are stair-stepped; perform a mesh-refinement study before interpreting engineering results.</p>';break;
    case 'materials':heading='Material properties';html=hero('material','Fluid material','Constant density and dynamic viscosity')+select('fluid.preset','Material',c.fluid.name.startsWith('Water')?'water':c.fluid.name.startsWith('Air')?'air':c.fluid.name.startsWith('Glycerol')?'glycerol':'custom',[['water','Water · 20 °C'],['air','Air · 20 °C'],['glycerol','Glycerol · reference'],['custom','Custom material']])+input('fluid.density','Reference density',c.fluid.density,'kg/m³')+input('fluid.viscosity','Dynamic viscosity',c.fluid.viscosity,'Pa·s')+apply+`<div class="stats-card">${stat('Kinematic viscosity',formatNumber(p.nu)+' m²/s')}${stat('Reynolds number',formatNumber(p.Re,4))}${stat('Relaxation time τ+',p.tau.toFixed(5))}</div><p class="form-note">Material values map directly into lattice viscosity. Incompatible speed, grid, and viscosity combinations are rejected rather than silently stabilized by changing the physics.</p>`;break;
    case 'boundary':case 'inlet':case 'outlet':case 'walls':heading='Boundary conditions';html=hero('boundary',s.panel==='inlet'?'Velocity boundary':s.panel==='outlet'?'Pressure outlet':s.panel==='walls'?'Wall conditions':'Boundary conditions',p.mode===1?'Closed cavity · moving top lid':'Velocity inlet · gauge pressure outlet')+label(p.mode===1?'Moving lid':'Inlet')+input('flow.speed',p.mode===1?'Lid velocity':'Inlet reference velocity',c.flow.speed,'mm/s',1000)+select('flow.profile','Inlet profile',c.flow.profile,[['uniform','Uniform'],['parabolic','Parabolic (peak = reference)']])+label('Lateral boundaries')+select('flow.walls','Top / bottom',c.flow.walls,[['noslip','Stationary no-slip walls'],['periodic','Periodic pair']])+apply+`<div class="stats-card">${stat('Outlet gauge pressure','0 Pa')}${stat('Obstacle surfaces','No slip')}${stat('Inlet reconstruction','Zou–He')}${stat('Outlet reconstruction','Zou–He ρ = 1')}</div><p class="form-note">${p.mode===1?'Cavity mode overrides inlet/outlet and lateral selections: the top lid moves; all other perimeter walls are fixed.':'Prescribed inlet velocity and outlet density. The lateral periodic option removes the top/bottom wall pair.'}</p>`;break;
    case 'models':heading='Physical models';html=hero('settings','Flow formulation','Weakly compressible · low-Mach regime')+`<div class="tag-row"><span class="selected">Laminar</span><span>2D planar</span><span>Isothermal</span></div>`+label('Collision operator')+select('solver.collision','Relaxation model',c.solver.collision,[['trt','Two-relaxation-time (TRT)'],['bgk','Single-relaxation-time (BGK)']])+input('flow.latticeSpeed','Lattice reference velocity',c.flow.latticeSpeed,'lu/ts',1,.005)+apply+`<div class="stats-card">${stat('Lattice','D2Q9')}${stat('τ+ (viscous)',p.tau.toFixed(5))}${stat('ω− (odd)',p.odd.toFixed(5))}${stat('TRT magic parameter','3/16')}${stat('Nominal Mach',(p.u*Math.sqrt(3)).toFixed(3))}</div><p class="form-note warning">No turbulence closure, energy equation, multiphase model, reacting flow, or 3D solver is implemented. This workbench is not an Ansys Fluent engine or file-format replacement.</p>`;break;
    case 'results':heading='Display properties';html=hero('contour','Field visualization','Data comes directly from the flow solver.')+select('display.field','Color by',c.display.field,Object.entries(FIELDS).map(([v,t])=>[v,t.label]))+select('display.palette','Color map',c.display.palette,[['spectrum','Spectrum'],['viridis','Viridis'],['ice','Ice'],['diverging','Diverging']])+check('display.autoRange','Automatic range',c.display.autoRange)+`<div class="form-pair">${input('display.rangeMin','Minimum',c.display.rangeMin)}${input('display.rangeMax','Maximum',c.display.rangeMax)}</div>`+label('Overlays')+check('display.streamlines','Streamlines',c.display.streamlines)+check('display.vectors','Velocity vectors',c.display.vectors)+check('display.particles','Passive tracers',c.display.particles)+check('display.contours','Contour bands',c.display.contours)+check('display.mesh','Lattice grid',c.display.mesh)+secondary('apply-display','Apply display','check','accent')+label('Export results')+secondary('screenshot','Save viewport image','camera')+secondary('csv','Export field CSV','download')+secondary('vtk','Export field VTK','cube');break;
    case 'probes':heading='Probe points';html=hero('probe','Point measurements','Sample the latest measured flow field.')+secondary('probe-tool','Place a probe in the domain','plus','accent')+c.probes.map(pr=>{const v=s.field?sample(s.field,p,pr.x,pr.y):null;return `<div class="stats-card">${stat(esc(pr.name),`${formatNumber(pr.x*1000)}, ${formatNumber(pr.y*1000)} mm`)}${stat('Velocity',v?formatNumber(v.speed)+' m/s':'—')}${stat('Gauge pressure',v?formatNumber(v.pressure)+' Pa':'—')}<button class="button-secondary" data-delete-probe="${esc(pr.id)}">Remove probe</button></div>`;}).join('')+secondary('export-probes','Export probe data','download')+secondary('clear-probes','Clear all probes','trash')+'<p class="form-note">Probe sampling uses the nearest lattice node. Solid cells report zero velocity. Export includes the solution iteration and physical time.</p>';break;
    case 'report':heading='Case report';html=hero('file','Simulation summary','Measured diagnostics and numerical setup')+`<div class="stats-card">${stat('Reynolds number',formatNumber(p.Re,4))}${stat('Reference length',formatNumber(p.charLength*1000)+' mm')}${stat('Iteration',s.iteration.toLocaleString())}${stat('Physical time',formatNumber(s.iteration*p.dt)+' s')}${stat('Maximum Mach',d?d.mach.toFixed(4):'—')}${stat('Mean lattice density',d?d.meanRho.toFixed(6):'—')}${stat('Flux mismatch',p.mode===1?'Closed cavity':(d?d.imbalance.toFixed(2)+' %':'—'))}</div>`+secondary('export-report','Export report JSON','download')+secondary('csv','Export field CSV','download')+'<p class="form-note">Inlet/outlet flux mismatch is a transient flow-rate diagnostic, not a full discrete mass-conservation residual. Gauge pressure is relative to the outlet reference density.</p>';break;
    case 'solution':default:heading='Solution setup';html=hero('cpu','Run calculation','Transient · lattice Boltzmann method')+`<div class="tag-row"><span class="selected">2D planar</span><span>Laminar</span><span>Isothermal</span></div>`+label('Solution method')+select('solver.collision','Collision operator',c.solver.collision,[['trt','Two-relaxation-time (TRT)'],['bgk','Single-relaxation-time (BGK)']])+`<div class="stats-card">${stat('Time discretization','Explicit')}${stat('Physical time step',formatNumber(p.dt)+' s')}${stat('Reynolds number',formatNumber(p.Re,4))}</div>`+label('Run controls')+input('solver.target','Target iteration',c.solver.target,'steps',1,1000)+select('solver.batch','Iterations per frame',c.solver.batch,[1,4,8,12,24,32,64].map(v=>[v,String(v)]))+input('solver.tolerance','Temporal residual threshold',c.solver.tolerance,'',1,.00001)+check('solver.autoStop','Stop on temporal convergence',c.solver.autoStop)+apply+`<p class="form-note">Convergence requires both velocity changes below the threshold for 8 consecutive samples, with at least 100 iterations between checks.</p>`+secondary('initialize','Reinitialize solution','reset');break;
  }
  qs('#inspector-heading').textContent=heading;qs('#inspector').innerHTML=html;
}
export function renderBottom(s){const host=qs('#bottom-content');if(!s.field&&s.bottom==='probes'){host.innerHTML='<div class="empty-state">Initializing probe field…</div>';return;}if(s.bottom==='convergence'){if(!qs('#chart-canvas'))host.innerHTML=`<div class="monitor-chart"><div class="chart-caption"><span>Temporal residuals <span class="subtle">· normalized change / iteration</span></span><div class="chart-key"><span><i class="line-orange"></i>density</span><span><i class="line-blue"></i>x-velocity</span><span><i class="line-green"></i>y-velocity</span></div></div><canvas id="chart-canvas"></canvas></div><div class="monitor-numbers"><div><span>Iteration</span><strong id="metric-iteration">0</strong><small id="metric-target"></small></div><div><span>Physical time</span><strong id="metric-time"></strong></div><div><span>Max. velocity</span><strong id="metric-speed"></strong></div><div class="monitor-state" id="monitor-health"><i></i>Within checks</div></div>`;
    qs('#metric-iteration').textContent=s.iteration.toLocaleString();qs('#metric-target').textContent=`of ${s.case.solver.target.toLocaleString()}`;qs('#metric-time').innerHTML=`${(s.iteration*s.p.dt).toFixed(2)} <small>s</small>`;qs('#metric-speed').innerHTML=`${formatNumber(s.diag?.range.speed[1]??0)} <small>m/s</small>`;qs('#monitor-health').innerHTML=`<i style="background:${s.diag?.unstable?'#d56a60':s.diag?.mach>.25?'#d5a251':'#5bb49a'}"></i> ${s.diag?.unstable?'Stability limit exceeded':s.diag?.mach>.25?'Elevated lattice Mach':'Within numerical checks'}`;drawChart(qs('#chart-canvas'),s.records);
  }else if(s.bottom==='console'){host.innerHTML='<div class="console-view">'+s.logs.map(l=>`<div class="console-entry"><time>${esc(l.time)}</time><span class="log-${l.level}">${esc(l.message)}</span></div>`).join('')+'</div>';const el=host.firstElementChild;el.scrollTop=el.scrollHeight;
  }else if(s.bottom==='probes'){if(!s.case.probes.length){host.innerHTML='<div class="empty-state"><strong>Inspect the flow, point by point.</strong>Choose the probe tool or press P, then click inside the domain.</div>';return;}host.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Probe</th><th>X (mm)</th><th>Y (mm)</th><th>Speed (m/s)</th><th>u (m/s)</th><th>v (m/s)</th><th>Pressure (Pa)</th></tr></thead><tbody>${s.case.probes.map(pr=>{const v=sample(s.field,s.p,pr.x,pr.y);return `<tr><td>${esc(pr.name)}</td><td>${formatNumber(pr.x*1000)}</td><td>${formatNumber(pr.y*1000)}</td><td>${formatNumber(v?.speed)}</td><td>${formatNumber(v?.ux)}</td><td>${formatNumber(v?.uy)}</td><td>${formatNumber(v?.pressure)}</td></tr>`;}).join('')}</tbody></table></div>`;
  }else{const p=s.p,d=s.diag;host.innerHTML=`<div class="report-view">${stat('Solver','D2Q9 / '+s.case.solver.collision.toUpperCase())}${stat('Compute backend',s.backend)}${stat('Mesh',`${p.nx} × ${p.ny}`)}${stat('Reynolds number',formatNumber(p.Re,4))}${stat('Lattice Mach',d?d.mach.toFixed(4):'—')}${stat('Time step',formatNumber(p.dt)+' s')}${stat('Mean density',d?d.meanRho.toFixed(6):'—')}${stat('Fluid cells',d?.count?.toLocaleString()??'—')}${stat('Gauge pressure span',d?formatNumber(d.range.pressure[1]-d.range.pressure[0])+' Pa':'—')}<div class="report-note">2D, isothermal, laminar, weakly compressible flow. Pressure excludes viscous stress. No turbulence closure or engineering certification. Verify against benchmark solutions and mesh-refinement studies.</div></div>`;}
}
export function syncUI(s){qs('#project-title').innerHTML=esc(s.case.name)+' <span>⌄</span>';qs('#graphics-case').textContent=s.case.name.toLowerCase().replaceAll(' ','-');qs('#scene-title').textContent=s.case.name;qs('#scene-subtitle').textContent=`${s.case.bodies.some(b=>b.type==='airfoil')?'NACA '+String(Math.round((s.case.bodies.find(b=>b.type==='airfoil')?.thickness??.12)*100)).padStart(4,'0')+' · ':''}${s.p.mode===1?'Moving-lid benchmark':s.case.bodies.length?'Resolved solid boundaries':'Internal laminar flow'} · Re ${formatNumber(s.p.Re,4)}`;
  qs('#field-select').value=s.case.display.field;const f=FIELDS[s.case.display.field];qs('#field-unit').textContent=f.unit;qs('#scene-field').textContent=f.label.toUpperCase();qs('#legend-title').textContent=f.legend;qs('#legend-unit').textContent=f.unit;
  document.querySelectorAll('[data-toggle]').forEach(el=>el.classList.toggle('active',s.case.display[el.dataset.toggle]));document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('active',s.tool===el.dataset.tool));document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',s.ribbonTab===el.dataset.tab));document.querySelectorAll('[data-bottom]').forEach(el=>el.classList.toggle('active',s.bottom===el.dataset.bottom));
  qs('#scene-status').textContent=s.running?'Calculating':s.loading?'Initializing':'Paused';qs('#run-dot').classList.toggle('running',s.running);qs('#iteration-label').textContent=`${s.iteration.toLocaleString()} iterations`;qs('#footer-state').textContent=s.running?'Calculation in progress':s.iteration?'Solution paused':'Ready to calculate';qs('#run-main').innerHTML=icon(s.running?'pause':'play')+`<span>${s.running?'Pause calculation':'Calculate'}</span><kbd>Space</kbd>`;
  qs('#status-cells').textContent=`${s.p.n.toLocaleString()} cells`;qs('#status-re').textContent=`Re ${formatNumber(s.p.Re,4)}`;qs('#status-tau').textContent=`τ ${s.p.tau.toFixed(4)}`;qs('#status-backend').textContent=s.backend;qs('#log-count').textContent=s.logs.length;qs('#loading').hidden=!s.loading;
}
