import {outline,clamp} from './model.js';
import {bilinearVelocity} from './diagnostics.js';
export const PALETTES={spectrum:[[.07,.09,.38],[.08,.30,.80],[0,.74,.84],[.37,.89,.51],[.99,.81,.21],[.94,.21,.16]],viridis:[[.267,.005,.329],[.254,.265,.529],[.164,.471,.558],[.134,.659,.518],[.478,.821,.318],[.993,.906,.144]],ice:[[.03,.05,.14],[.1,.21,.43],[.08,.4,.66],[.11,.65,.83],[.45,.85,.88],[.95,1,1]],diverging:[[.14,.26,.69],[.28,.53,.85],[.69,.82,.93],[.95,.78,.65],[.86,.38,.29],[.57,.08,.16]]};
export const FIELDS={speed:{label:'Velocity magnitude',legend:'Velocity',unit:'m/s',index:0},pressure:{label:'Gauge pressure',legend:'Pressure',unit:'Pa',index:1},vorticity:{label:'Vorticity · Z',legend:'Vorticity',unit:'s⁻¹',index:2},ux:{label:'X velocity',legend:'X velocity',unit:'m/s',index:3},uy:{label:'Y velocity',legend:'Y velocity',unit:'m/s',index:4}};
export function colorAt(t,palette){const a=PALETTES[palette]??PALETTES.spectrum,k=clamp(t,0,1)*5,i=Math.min(4,Math.floor(k)),f=k-i;return a[i].map((v,j)=>Math.round((v*(1-f)+a[i+1][j]*f)*255));}
export function formatNumber(v,digits=3){if(!Number.isFinite(v))return '—';if(v===0)return '0';if(Math.abs(v)<.001||Math.abs(v)>=1e5)return v.toExponential(2);return Number(v.toPrecision(digits)).toString();}
/** GPU scalar rendering is zero-copy. Geometry, axes and measured streamlines use a lightweight overlay. */
export class Viewport {
  constructor(getState){this.getState=getState;this.host=document.querySelector('#viewport');this.canvas=document.querySelector('#field-canvas');this.overlay=document.querySelector('#overlay-canvas');this.ctx=this.overlay.getContext('2d');this.zoom=1;this.pan=[0,0];this.lines=[];this.particles=[];this.lastParticleIteration=0;this.flowStamp=-1;this.rasterStamp=-1;this.cpuCanvas=document.createElement('canvas');this.cpuCtx=this.cpuCanvas.getContext('2d');this.draft=null;this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(this.host);this.resize();}
  resize(){const r=this.host.getBoundingClientRect();this.width=r.width;this.height=r.height;this.dpr=Math.min(devicePixelRatio||1,2);for(const c of [this.canvas,this.overlay]){c.width=Math.max(1,Math.round(r.width*this.dpr));c.height=Math.max(1,Math.round(r.height*this.dpr));}this.rect();}
  resetCanvas(){const old=this.canvas;this.canvas=old.cloneNode(false);old.replaceWith(this.canvas);this.resize();this.cpuContext=null;}
  rect(){const s=this.getState();if(!s.p)return;const {nx,ny}=s.p;const left=62,right=this.width<500?80:100,top=143,bottom=55;const w=Math.max(100,this.width-left-right),h=Math.max(80,this.height-top-bottom);const scale=Math.min(w/(nx-1),h/(ny-1))*this.zoom;const dw=(nx-1)*scale,dh=(ny-1)*scale;this.box={x:left+w/2-dw/2+this.pan[0],y:top+h/2-dh/2+this.pan[1],w:dw,h:dh,scale};return this.box;}
  fit(){this.zoom=1;this.pan=[0,0];this.rect();document.querySelector('#zoom-label').textContent='100%';}
  zoomAt(x,y,amount){const b=this.rect(),gx=(x-b.x)/b.w,gy=(y-b.y)/b.h;this.zoom=clamp(this.zoom*amount,.45,12);const n=this.rect();this.pan[0]+=x-(n.x+gx*n.w);this.pan[1]+=y-(n.y+gy*n.h);this.rect();document.querySelector('#zoom-label').textContent=`${Math.round(this.zoom*100)}%`;}
  world(x,y){const s=this.getState(),b=this.rect();return [(x-b.x)/b.w*s.case.domain.length,(1-(y-b.y)/b.h)*s.p.actualHeight];}
  screen(x,y){const s=this.getState(),b=this.box;return [b.x+x/s.case.domain.length*b.w,b.y+(1-y/s.p.actualHeight)*b.h];}
  reset(){this.lines=[];this.particles=[];this.flowStamp=-1;this.rasterStamp=-1;this.lastParticleIteration=0;}
  getRange(){const s=this.getState(),d=s.case.display;if(!d.autoRange)return [d.rangeMin,d.rangeMax];const r=s.diag?.range[d.field];let lo=r?.[0]??0,hi=r?.[1]??s.case.flow.speed*1.4;if(d.field==='speed'){lo=0;hi=Math.max(s.case.flow.speed*1.35,hi);}else if(d.field==='vorticity'||d.field==='pressure'||d.field==='uy'){const lim=Math.max(Math.abs(lo),Math.abs(hi),d.field==='pressure'?.001:1e-5);lo=-lim;hi=lim;}if(hi-lo<1e-12)hi=lo+1e-6;return [lo,hi];}
  renderGPU(){const s=this.getState(),b=this.box,raw=new ArrayBuffer(80),f=new Float32Array(raw),u=new Uint32Array(raw),range=this.getRange();f.set([this.canvas.width,this.canvas.height,b.x*this.dpr,b.y*this.dpr,b.w*this.dpr,b.h*this.dpr,s.p.nx,s.p.ny,range[0],range[1],s.p.speedScale,s.p.pressureScale]);u.set([FIELDS[s.case.display.field].index,Object.keys(PALETTES).indexOf(s.case.display.palette),s.case.display.mesh?1:0,s.case.display.contours?1:0],12);f.set([.032,.048,.077,1/(2*s.p.dt)],16);s.renderer.render(raw);}
  renderCPU(){const s=this.getState(),p=s.p,d=s.case.display;if(!this.cpuContext)this.cpuContext=this.canvas.getContext('2d');const ctx=this.cpuContext,b=this.box;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.fillStyle='#080c14';ctx.fillRect(0,0,this.width,this.height);ctx.strokeStyle='#ffffff05';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<this.width;x+=32){ctx.moveTo(x,0);ctx.lineTo(x,this.height);}for(let y=0;y<this.height;y+=32){ctx.moveTo(0,y);ctx.lineTo(this.width,y);}ctx.stroke();
    const key=[s.snapshotIteration,d.field,d.palette,d.mesh,d.contours,...this.getRange()].join('/');
    if(key!==this.rasterStamp&&s.field){this.rasterStamp=key;this.cpuCanvas.width=p.nx;this.cpuCanvas.height=p.ny;const image=this.cpuCtx.createImageData(p.nx,p.ny),bytes=image.data,field=s.field,[lo,hi]=this.getRange();const lut=Array.from({length:256},(_,i)=>colorAt(i/255,d.palette));
      for(let y=0;y<p.ny;y++)for(let x=0;x<p.nx;x++){const i=y*p.nx+x,j=i*4,k=((p.ny-1-y)*p.nx+x)*4;let rgb;
        if(field[j+3]>.5)rgb=[31,41,56];else{let val;
          if(d.field==='pressure')val=(field[j+2]-1)*p.pressureScale;
          else if(d.field==='ux')val=field[j]*p.speedScale;else if(d.field==='uy')val=field[j+1]*p.speedScale;
          else if(d.field==='vorticity'){const l=(Math.max(0,x-1)+y*p.nx)*4,r=(Math.min(p.nx-1,x+1)+y*p.nx)*4,bo=(Math.max(0,y-1)*p.nx+x)*4,t=(Math.min(p.ny-1,y+1)*p.nx+x)*4;val=((field[r+1]-field[l+1])-(field[t]-field[bo]))/(2*p.dt);}
          else val=Math.hypot(field[j],field[j+1])*p.speedScale;
          const norm=(val-lo)/(hi-lo);rgb=lut[clamp(Math.round(norm*255),0,255)];if(d.contours&&Math.abs((norm*18)%1-.5)<.035)rgb=rgb.map(v=>v*.7);
        }bytes[k]=rgb[0];bytes[k+1]=rgb[1];bytes[k+2]=rgb[2];bytes[k+3]=255;
      }this.cpuCtx.putImageData(image,0,0);
    }
    ctx.imageSmoothingEnabled=true;ctx.drawImage(this.cpuCanvas,b.x,b.y,b.w,b.h);
    if(d.mesh&&b.scale>2){ctx.save();ctx.beginPath();ctx.rect(b.x,b.y,b.w,b.h);ctx.clip();ctx.strokeStyle='#101a2948';ctx.lineWidth=.5;ctx.beginPath();for(let x=0;x<p.nx;x++){const px=b.x+x*b.scale;ctx.moveTo(px,b.y);ctx.lineTo(px,b.y+b.h);}for(let y=0;y<p.ny;y++){const py=b.y+y*b.scale;ctx.moveTo(b.x,py);ctx.lineTo(b.x+b.w,py);}ctx.stroke();ctx.restore();}
  }
  buildLines(){const s=this.getState(),p=s.p,field=s.field;if(!field)return;this.lines=[];const seeds=[];
    if(p.mode===1){for(let y=2;y<p.ny-2;y+=p.ny/8)for(let x=2;x<p.nx-2;x+=p.nx/8)seeds.push([x,y]);}
    else for(let i=1;i<=29;i++)seeds.push([1.6,1.5+(p.ny-4)*i/30]);
    for(const seed of seeds){let [x,y]=seed;const line=[];for(let i=0;i<1000;i++){const v=bilinearVelocity(field,p,x,y);if(!v)break;const speed=Math.hypot(...v);if(speed<1e-6)break;line.push([x,y]);const ds=1.2,half=bilinearVelocity(field,p,x+v[0]/speed*ds*.5,y+v[1]/speed*ds*.5);if(!half)break;const norm=Math.hypot(...half);if(norm<1e-7)break;x+=half[0]/norm*ds;y+=half[1]/norm*ds;if(p.mode===1&&line.length>15&&Math.hypot(x-seed[0],y-seed[1])<1.7)break;}if(line.length>3)this.lines.push(line);}
  }
  drawOverlay(){const s=this.getState(),ctx=this.ctx,b=this.box,p=s.p;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.width,this.height);if(!s.field)return;
    ctx.save();ctx.beginPath();ctx.rect(b.x,b.y,b.w,b.h);ctx.clip();
    if(s.case.display.streamlines){if(this.flowStamp!==s.snapshotIteration){this.buildLines();this.flowStamp=s.snapshotIteration;}ctx.lineWidth=.75;ctx.strokeStyle='#e9ffff42';for(const line of this.lines){ctx.beginPath();line.forEach(([x,y],i)=>{const sx=b.x+x*b.scale,sy=b.y+b.h-y*b.scale;i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy);});ctx.stroke();}}
    if(s.case.display.particles){if(!this.particles.length){for(let i=0;i<230;i++)this.particles.push([1.5+((i*127.127)%1)*(p.nx-4),2+((i*.61803398875)%1)*(p.ny-4)]);}
      const elapsed=Math.max(0,s.iteration-this.lastParticleIteration);this.lastParticleIteration=s.iteration;ctx.strokeStyle='#e0ffff90';ctx.lineWidth=1.1;
      for(const a of this.particles){const old=[...a],velocity=bilinearVelocity(s.field,p,...a);if(!velocity||a[0]>p.nx-3){a[0]=p.mode===1?2+Math.random()*(p.nx-4):2;a[1]=2+Math.random()*(p.ny-4);continue;}
        const n=Math.max(1,Math.ceil(Math.min(elapsed,96)/12)),dt=Math.min(elapsed,96)/n;for(let k=0;k<n;k++){const v=bilinearVelocity(s.field,p,...a);if(!v)break;const half=bilinearVelocity(s.field,p,a[0]+v[0]*dt*.5,a[1]+v[1]*dt*.5)??v;a[0]+=half[0]*dt;a[1]+=half[1]*dt;}
        if(Math.hypot(a[0]-old[0],a[1]-old[1])<20){ctx.beginPath();ctx.moveTo(b.x+a[0]*b.scale,b.y+b.h-a[1]*b.scale);ctx.lineTo(b.x+(a[0]-velocity[0]*9)*b.scale,b.y+b.h-(a[1]-velocity[1]*9)*b.scale);ctx.stroke();}
      }
    }else this.lastParticleIteration=s.iteration;
    if(s.case.display.vectors){const step=Math.max(8,Math.round(23/b.scale));ctx.strokeStyle='#e6ffff8c';ctx.lineWidth=.9;for(let y=3;y<p.ny-2;y+=step)for(let x=3;x<p.nx-2;x+=step){const j=(y*p.nx+x)*4;if(s.field[j+3]>.5)continue;const ux=s.field[j],uy=s.field[j+1],sp=Math.hypot(ux,uy);if(sp<1e-6)continue;const length=clamp(sp/p.u*12,2,20),sx=b.x+x*b.scale,sy=b.y+b.h-y*b.scale,ex=sx+ux/sp*length,ey=sy-uy/sp*length,a=Math.atan2(ey-sy,ex-sx);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);ctx.moveTo(ex-4*Math.cos(a-.45),ey-4*Math.sin(a-.45));ctx.lineTo(ex,ey);ctx.lineTo(ex-4*Math.cos(a+.45),ey-4*Math.sin(a+.45));ctx.stroke();}}
    ctx.restore();
    // Domain border and the dimensional ruler remain outside the field clip.
    ctx.strokeStyle='#7793af60';ctx.lineWidth=.8;ctx.strokeRect(b.x,b.y,b.w,b.h);
    ctx.font='8px "SFMono-Regular",Consolas,monospace';ctx.fillStyle='#7289a3';ctx.textAlign='center';ctx.strokeStyle='#5f78914d';ctx.lineWidth=.6;ctx.beginPath();
    for(let i=0;i<=6;i++){const x=b.x+b.w*i/6;ctx.moveTo(x,b.y+b.h);ctx.lineTo(x,b.y+b.h+5);ctx.fillText((s.case.domain.length*1000*i/6).toFixed(0),x,b.y+b.h+16);}ctx.stroke();ctx.fillStyle='#4e6680';ctx.textAlign='left';ctx.fillText('mm',b.x+b.w+11,b.y+b.h+16);
    // Boundary condition identifiers.
    ctx.save();ctx.translate(b.x-12,b.y+b.h/2);ctx.rotate(-Math.PI/2);ctx.font='7px Inter, sans-serif';ctx.letterSpacing='1px';ctx.textAlign='center';ctx.fillStyle='#91c5cbaa';ctx.fillText(p.mode===1?'NO-SLIP WALL':'VELOCITY INLET',0,0);ctx.restore();
    ctx.save();ctx.translate(b.x+b.w+13,b.y+b.h/2);ctx.rotate(Math.PI/2);ctx.font='7px Inter, sans-serif';ctx.textAlign='center';ctx.fillStyle='#9da7bd99';ctx.fillText(p.mode===1?'NO-SLIP WALL':'PRESSURE OUTLET',0,0);ctx.restore();
    ctx.textAlign='left';ctx.font='7px Inter, sans-serif';ctx.fillStyle='#7192a280';ctx.fillText(p.mode===1?'MOVING LID →':s.case.flow.walls==='noslip'?'NO-SLIP WALL':'PERIODIC PAIR',b.x+7,b.y-8);
    for(const body of s.case.bodies){const poly=outline(body),selected=body.id===s.selected;ctx.beginPath();poly.forEach(([x,y],i)=>{const pt=this.screen(x,y);i?ctx.lineTo(...pt):ctx.moveTo(...pt);});ctx.closePath();ctx.fillStyle='#273545';ctx.fill();ctx.strokeStyle=selected?'#eec16c':'#c6d5e3bb';ctx.lineWidth=selected?1.5:.9;ctx.stroke();
      if(selected){const [sx,sy]=this.screen(body.x,body.y);ctx.setLineDash([3,3]);ctx.strokeStyle='#e9be6450';ctx.beginPath();ctx.moveTo(sx-11,sy);ctx.lineTo(sx+11,sy);ctx.moveTo(sx,sy-11);ctx.lineTo(sx,sy+11);ctx.stroke();ctx.setLineDash([]);const xs=poly.map(v=>v[0]),ys=poly.map(v=>v[1]);for(const pt of [[Math.min(...xs),Math.min(...ys)],[Math.min(...xs),Math.max(...ys)],[Math.max(...xs),Math.min(...ys)],[Math.max(...xs),Math.max(...ys)]]){const [x,y]=this.screen(...pt);ctx.fillStyle='#efc475';ctx.fillRect(x-2,y-2,4,4);}ctx.font='8px Inter, sans-serif';ctx.textAlign='center';ctx.fillStyle='#eac77f';ctx.fillText(body.name,sx,sy+Math.max(body.height/p.dx*b.scale/2,10)+16);}
    }
    for(let i=0;i<s.case.probes.length;i++){const probe=s.case.probes[i],[x,y]=this.screen(probe.x,probe.y);ctx.strokeStyle='#f6c471';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.moveTo(x-8,y);ctx.lineTo(x+8,y);ctx.moveTo(x,y-8);ctx.lineTo(x,y+8);ctx.stroke();ctx.fillStyle='#f4d094';ctx.textAlign='left';ctx.font='8px Inter, sans-serif';ctx.fillText(probe.name,x+9,y-6);}
    if(this.draft){ctx.strokeStyle='#f2c16b';ctx.fillStyle='#f2c16b22';ctx.lineWidth=1;ctx.setLineDash([4,3]);ctx.beginPath();if(this.draft.type==='polygon'){this.draft.points.forEach((v,i)=>{const pt=this.screen(...v);i?ctx.lineTo(...pt):ctx.moveTo(...pt);});}else{const [a,bb]=this.draft.points,aa=this.screen(...a),cc=this.screen(...bb);if(this.draft.type==='circle'){const r=Math.hypot(cc[0]-aa[0],cc[1]-aa[1]);ctx.arc(aa[0],aa[1],r,0,Math.PI*2);}else ctx.rect(aa[0],aa[1],cc[0]-aa[0],cc[1]-aa[1]);}ctx.fill();ctx.stroke();ctx.setLineDash([]);}
    // A small world-axis orientation glyph.
    const ox=25,oy=this.height-53;ctx.lineWidth=1;ctx.strokeStyle='#b46664';ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ox+19,oy);ctx.stroke();ctx.strokeStyle='#63a79e';ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ox,oy-19);ctx.stroke();ctx.font='7px Inter, sans-serif';ctx.textAlign='center';ctx.fillStyle='#b67d7b';ctx.fillText('x',ox+25,oy+2);ctx.fillStyle='#71a99f';ctx.fillText('y',ox,oy-24);ctx.fillStyle='#97a7b8';ctx.beginPath();ctx.arc(ox,oy,2,0,Math.PI*2);ctx.fill();
  }
  draw(){const s=this.getState();if(!s.p||!s.field)return;this.rect();if(s.renderer)this.renderGPU();else this.renderCPU();this.drawOverlay();}
}
export function drawChart(canvas,history){if(!canvas)return;const r=canvas.getBoundingClientRect();if(r.width<1||r.height<1)return;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const dark=document.documentElement.dataset.theme==='dark',left=37,top=9,w=r.width-left-8,h=r.height-top-20;ctx.lineWidth=.65;ctx.font='7px monospace';ctx.textAlign='right';ctx.fillStyle=dark?'#66788f':'#8b97a4';ctx.strokeStyle=dark?'#313946':'#e7ebef';for(let i=0;i<5;i++){const y=top+h*i/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+w,y);ctx.stroke();ctx.fillText(`1e-${i+2}`,left-7,y+2);}const maxIteration=Math.max(1000,history.at(-1)?.iteration??0);ctx.textAlign='center';for(let i=0;i<5;i++)ctx.fillText(Math.round(maxIteration*i/4).toLocaleString(),left+w*i/4,top+h+13);if(!history.length){ctx.font='10px Inter, sans-serif';ctx.fillStyle=dark?'#8594a9':'#9ba5af';ctx.fillText('Measured residuals appear as the solver advances',left+w/2,top+h/2);return;}for(const [key,color] of [['density','#d8a04a'],['x','#628ecc'],['y','#5db194']]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=1.15;let first=true;for(const row of history){if(!row.residual)continue;const val=Math.max(1e-6,row.residual[key]),x=left+w*row.iteration/maxIteration,y=top+clamp((-Math.log10(val)-2)/4,0,1)*h;first?ctx.moveTo(x,y):ctx.lineTo(x,y);first=false;}ctx.stroke();}}
